# https://docs.docker.com/engine/reference/builder/#env
# FROM java:8
# FROM openjdk:8-jre-alpine  
FROM gcr.io/distroless/java:8
# FROM gcr.io/distroless/java:latest
COPY ./target/sbapp-1.0-SNAPSHOT-jar-with-dependencies.jar /var/www/java/  
WORKDIR /var/www/java   
ENV _JAVA_OPTIONS="${_JAVA_OPTIONS}" 
ENV VM_NAME=${VM_NAME} 
ENV PROBLEM_ROW=${PROBLEM_ROW}
ENV PROBLEM_COL=${PROBLEM_COL}
ENTRYPOINT ["java","-jar","sbapp-1.0-SNAPSHOT-jar-with-dependencies.jar"]
